<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/03/18 23:13:41

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=conlallave_db',
  'username' => 'conlallave_db',
  'password' => 'zAw4f7r66VnhYpHw',
  'name' => 'doctrine',
)),);
