Contact:
  actAs:
    Timestampable: ~
  columns:
    name:         { type: string(100), notnull: true }
    email:        { type: string(100), notnull: true }
    phone:        { type: string(20), notnull: true }
    utm_source:   { type: string(100), notnull: false }
    utm_medium:   { type: string(100), notnull: false }
    utm_campaign: { type: string(100), notnull: false, default: 'landing_v1'}