<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/03/18 13:13:31

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=conlallave',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
